Resources:
  Entities:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.entities}
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  Events:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.events}
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: eventId-index
          KeySchema:
            - AttributeName: hashKey
              KeyType: HASH
            - AttributeName: eventId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  Evaluations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.evaluations}
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
        - AttributeName: question
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: QuestionLSI
          KeySchema:
            - AttributeName: hashKey
              KeyType: HASH
            - AttributeName: question
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  Registrations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.registrations}
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
        - AttributeName: registrationId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: RegistrationIdIndex
          KeySchema:
            - AttributeName: registrationId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      LocalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: hashKey
              KeyType: HASH
            - AttributeName: email
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  PreRegistrations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.preregistrations}
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
        - AttributeName: preRegistrationId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: PreRegistrationIdIndex
          KeySchema:
            - AttributeName: preRegistrationId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      LocalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: hashKey
              KeyType: HASH
            - AttributeName: email
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  EntitiesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.stage}-sparcs-events-entities
      Type: String
      Value: ${self:custom.entities}

  RegistrationsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.stage}-sparcs-events-registrations
      Type: String
      Value: ${self:custom.registrations}

  PreRegistrationsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.stage}-sparcs-events-preregistrations
      Type: String
      Value: ${self:custom.preregistrations}

  EvaluationsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.stage}-sparcs-events-evaluations
      Type: String
      Value: ${self:custom.evaluations}

  EventsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.stage}-sparcs-events-events
      Type: String
      Value: ${self:custom.events}
