Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.bucket}-2
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, HEAD]
            AllowedOrigins: ["*"]
            Id: ${self:custom.bucket}-name
            MaxAge: "3600"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:custom.stage}-sparcs-events-file-bucket
      Type: String
      Value: ${self:custom.bucket}
